services:

  joy2twist:
    image: husarion/joy2twist:noetic
    restart: unless-stopped
    tty: true
    network_mode: host
    ipc: host
    devices:
      - /dev/input/js0
    environment:
      - ROS_IP=10.15.20.2
      - ROS_MASTER_URI=http://10.15.20.2:11311
    command: >
      roslaunch --wait
      joy2twist gamepad_controller.launch
      joy2twist_params_file:=$(find joy2twist)/config/joy2twist_panther.yaml
